### ISSUE TITLE
可以支援繁體中文? exception印出都會出現亂碼

### ISSUE THREAD

**Issue by linchao0815** [focus-creative-games/luban#2]

**Comment by pirunxi** [comment]
可以的。你有QQ吗？ 能否加入QQ群：692890842 联系？ 这样方便配合反馈

**Comment by pirunxi** [comment]
我尝试了将本地语言切到 台湾繁体，但好像没有乱码，只不过打印出来的都是简体中文。  如有可能，请注册QQ或者微信 跟我们保持联系，方便反馈和解决问题。 我们很快会考虑解决语言本地化的问题，至少提供（简体，繁体和英文）

**Comment by linchao0815** [comment]
2021-07-29 13:58:42.4406|====== load mission.TbDailyMission cost 557 ms ======
2021-07-29 13:58:42.4414|====== load mission.TbTestString cost 557 ms ======
2021-07-29 13:58:42.5205|GenJob fail. err:JOB_EXCEPTION msg:"配置文件:每日積分達成獎勵@任務.xlsx 生成失?. ==> sheet:每日積分達成獎 勵 ==> ?取?构:mission.DailyAcumPrize 字段:REWARDID2 位置:[M:5]  出? ==> cell:[L:5]  缺少?据    at Luban.Job.Cfg.DataCreators.ExcelNamedRowDataCreator.CreateBeanFields(DefBean bean, NamedRow row)
   at Luban.Job.Cfg.DataCreators.ExcelNamedRowDataCreator.Accept(TBean type, NamedRow row, Boolean multirow, Boolean nullable)
   at Luban.Job.Cfg.DataCreators.ExcelNamedRowDataCreator.ReadExcel(NamedRow row, TBean btype)
   at Luban.Job.Cfg.DataSources.Excel.Sheet.ReadOne(TBean type, Boolean enableMultiRowRecord)
   at Luban.Job.Cfg.DataSources.Excel.Sheet.ReadMulti(TBean type, Boolean enableMultiRowRecord)
   at Luban.Job.Cfg.DataSources.Excel.ExcelDataSource.ReadMulti(TBean type)
    at Luban.Job.Cfg.Utils.DataLoaderUtil.LoadCfgRecords(TBean recordType, String originFile, String sheetName, Byte[] content, Boolean multiRecord, Boolean exportTestData)
   at Luban.Job.Cfg.Utils.DataLoaderUtil.<>c__DisplayClass3_1.<<GenerateLoadRecordFromFileTasksAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Luban.Job.Cfg.Utils.DataLoaderUtil.LoadTableAsync(RemoteAgent agent, DefTable table, String dataDir, String branchName, String branchDataDir, Boolean exportTestData)
   at Luban.Job.Cfg.Utils.DataLoaderUtil.<>c__DisplayClass5_1.<<LoadCfgDataAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Luban.Job.Cfg.Utils.DataLoaderUtil.LoadCfgDataAsync(RemoteAgent agent, DefAssembly ass, String dataDir, String branchName, String branchDataDir, Boolean exportTestData)
   at Luban.Job.Cfg.JobController.<>c__DisplayClass8_0.<<GenAsync>g__CheckLoadCfgDataAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Luban.Job.Cfg.JobController.GenAsync(RemoteAgent agent, GenJob rpc)"
2021-07-29 13:58:42.5353|====== "gen job" cost 1211 ms ======
2021-07-29 13:58:42.5353|====== "generation" cost 1319 ms ======

**Comment by linchao0815** [comment]
win10/設定/語言/地區/系統管理語言設定/系統管理
非unicode 程式語言, 是使用"中文(繁體,台灣)
抱歉QQ太久沒用,無法使用手機認證XD

**Comment by pirunxi** [comment]
好的。我看看怎么解决哈。如果无乱码，但打印出简体中文能接受吗？ 我尽量今天解决这个问题哈。非常感谢使用和反馈。

**Comment by linchao0815** [comment]
> 好的。我看看怎么解决哈。如果无乱码，但打印出简体中文能接受吗？ 我尽量今天解决这个问题哈。非常感谢使用和反馈。

打印出简体中文能接受吗 -->OK,感謝

**Comment by pirunxi** [comment]
已解决。 可更新源码重新编译或者从 luban_examples项目中Tools目录获得最新编译的结果。或者 重新从docker pull 获取最新的luban-server:latest

**Comment by linchao0815** [comment]
> 已解决。 可更新源码重新编译或者从 luban_examples项目中Tools目录获得最新编译的结果。或者 重新从docker pull 获取最新的luban-server:latest

感謝,驗證OK
